name: Questionnaire Check - create & pending approval

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  issues: write
  contents: read

jobs:
  create-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Build issue link and create checks
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr = context.payload.pull_request;
            const headSha = pr.head.sha;
            const prNumber = pr.number;

            const title = encodeURIComponent(`Questionnaire for PR #${prNumber}`);
            const body = encodeURIComponent(`PR: #${prNumber}\n\n(please fill the form below)`);
            const issueUrl = `https://github.com/${owner}/${repo}/issues/new?template=questionnaire.yml&title=${title}&body=${body}`;

            await github.rest.checks.create({
              owner,
              repo,
              name: "Questionnaire Check / create-check",
              head_sha: headSha,
              status: "completed",
              conclusion: "success",
              output: {
                title: "Questionnaire link posted",
                summary: "A questionnaire issue link was added to this PR for approver input."
              }
            });

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `📝 Approver action required: please open the questionnaire form and submit or bypass.\n\nOpen form: ${issueUrl}`
            });

            await github.rest.checks.create({
              owner,
              repo,
              name: "Questionnaire Check / Questionnaire Approval",
              head_sha: headSha,
              status: "in_progress",
              output: {
                title: "Questionnaire required",
                summary: "This check stays in_progress until the questionnaire issue is submitted or bypassed."
              }
            });