name: Questionnaire Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { data: check } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Questionnaire Approval",
              head_sha: context.payload.pull_request.head.sha,
              status: "in_progress",
              output: {
                title: "Waiting for Approver",
                summary: "Approver must complete questionnaire OR bypass form."
              }
            });

            // Post link to form in PR comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚦 **Questionnaire Required**  
              Approver: Please fill out [the form](../../issues/new?template=questionnaire.yml&pr=${context.issue.number})`
            });
